name: audio_helper
description: Help you easier to add sounds and background music to your games or apps.
version: 0.1.1
homepage: https://github.com/lamnhan066/audio_helper

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

